source = "text04.tex"
output_directory = "artifacts/"

sequence = ["latex"] # Skip bibtex and makeindex

[programs.latex]
command = "lualatex"
opts  = [
    "--cnf-line='TEXINPUTS=.;../texmf//;'",
    "--shell-escape",
    "-file-line-error",
    "-interaction=nonstopmode",
    "-synctex=1",
    '-output-directory="%o"',
]
