source = ["text05.tex", "slide05.tex"]

sequence = ["latex"] # Skip bibtex and makeindex

[programs.latex]
command = "lualatex"
opts  = ["--shell-escape", "--cnf-line='TEXINPUTS=.;../texmf//;'"]
