source = ["text05.tex", "slide05.tex"]
output_directory = "artifacts/"

sequence = ["latex"] # Skip bibtex and makeindex

[programs.latex]
command = "lualatex"
opts  = ["--shell-escape", "--cnf-line='TEXINPUTS=.;../texmf//;'", '-output-directory="%o"', "-interaction=nonstopmode", "-file-line-error", "-synctex=1"]
